name: Run all tests

on:
  pull_request:
  push:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby:
          - 2.4
          - 2.5
          - 2.6
          - 2.7
        gemfile:
          - Gemfile
          - gemfiles/Gemfile.rails-4.2.x
          - gemfiles/Gemfile.rails-5.0.x
          - gemfiles/Gemfile.rails-5.1.x
          - gemfiles/Gemfile.rails-5.2.x
    name: Run gem tests
    steps:
      - uses: actions/checkout@v2
      - name: Setup ruby ${{ matrix.ruby }}
        uses: actions/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
      - name: Cache gems
        uses: actions/cache@v1
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-gems-${{ matrix.ruby }}
          restore-keys: |
            ${{ runner.os }}-gems-
      - name: Install gems
        run: |
          bundle config path vendor/bundle
          bundle install --gemfile=${{ matrix.gemfile }} \
                         --jobs 4 --retry 3
      - name: Run tests
        run: bundle exec rspec
